version: '2'
services:
    swoft-app:
       image: swoft/swoft:latest
       container_name: swoft-app
       volumes:
         - ./:/var/www/swoft
       stdin_open: true 
       tty: true
       privileged: true
       entrypoint: php /var/www/swoft/bin/swoft ws:start
    nginx-app:
      image: nginx
      container_name: nginx-app
      volumes:
         - ./:/var/www/swoft
         - ./nginx.conf:/etc/nginx/nginx.conf
         - /data/nginx/log/:/var/log/nginx/
      ports:
          - 80:80
      links: 
          - swoft-app   


